# Generated by Django 4.1.2 on 2022-10-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passanger", name="phone", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flightApp.flight"
            ),
        ),
    ]
