# Generated by Django 4.1.2 on 2022-10-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0002_alter_passanger_phone_alter_reservation_flight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight", old_name="flifhtNumber", new_name="flightNumber",
        ),
    ]
